version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    ports:
      - 1433:1433
    environment:
      MSSQL_SA_PASSWORD: Admin!Database
      ACCEPT_EULA: Y
      MSSQL_PID: Express
    command: /opt/mssql/bin/sqlservr
    volumes:
      - sqlvolume:/var/opt/mssql/data
      - ./DataAccess/CreateDatabase/entrypoint.sh:/entrypoint.sh
      - ./DataAccess/CreateDatabase/initialization.sh:/initialization.sh
      - ./DataAccess/CreateDatabase/initial-db-script.sql:/initial-db-script.sql

volumes:
  sqlvolume:
